plot.simrnet <- function(x,...){
    if(class(x)!="simrnet") stop("The class of \"x\" must be simrnet, which is generated by simrnet function.")
    oldpar = par()
    par(ask=TRUE) 
    par(mfrow=c(3,2)) 
    for(num.Sigma in 1:3){
        boxplot(x$RMSE[[num.Sigma]][[1]], xlab = "N", ylab = "RMSE",...)
        boxplot(x$RMSE[[num.Sigma]][[2]], xlab = "N", ylab = "RMSE",...)    
    }
    par(mfrow=c(3,2), ask=TRUE) 
    for(num.Sigma in 1:3){
        boxplot(x$R_square[[num.Sigma]][[1]], xlab = "N", ylab = "R_square",...)
        boxplot(x$R_square[[num.Sigma]][[2]], xlab = "N", ylab = "R_square",...)    
    }
    par(mfrow=oldpar$mfrow)
    par(ask=oldpar$ask)
}