plot.simrnet <- function(x,...){
    if(class(x)!="simrnet") stop("The class of \"x\" must be simrnet, which is generated by simrnet function.")
    par(mfrow=c(3,2)) 
    for(num.Sigma in 1:3){
        boxplot(x$RMSE[[num.Sigma]][[1]], xlab = "N", ylab = "RMSE",...)
        boxplot(x$RMSE[[num.Sigma]][[2]], xlab = "N", ylab = "RMSE",...)    
    }
    par(mfrow=c(1,1))
}